### PR TITLE
Decode space character from URL encoding to ASCII

### LINKED ISSUE #1625: AudioFuse Control Center PackageInfo not found in .pkg
I have tried to install the package to control my mixer in Darling, but installer immediately failed.

The package is available here: https://www.arturia.com/support/downloads-manuals/product/audiofuse-studio
In case the hotlink works: https://dl.arturia.net/products/afcc/soft/AudioFuse_Control_Center__2_3_0_1184.pkg

Suspect it's trying to use OS name and the package is for Mac OS so the nested pkg name is wrong.

```
Darling [/Volumes/SystemRoot/home/astralstorm/Downloads]$ installer -pkg AudioFuse_Control_Center__2_3_0_1184.pkg -target /
installer: Package name is AudioFuse Control Center
installer: Installing at base path /
installer: Installing selected choice AudioFuse Control Center Documentation
AudioFuse%20Control%20Center-2.3.0-Darwin-documentation.pkg/PackageInfo not found in .pkg
```

Versions:
Darwin transcendence 20.6.0 Darwin Kernel Version 20.6.0 x86_64
Linux transcendence 6.12.38+kali-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.12.38-1kali1 (2025-08-12) x86_64 GNU/Linux
Git commit: c431326ef3060a0e9814394ed919263d9c8f3f10

### PR DESCRIPTION
**Pull request by jlucfarias**
With that AudioFuse Control Center can be installed (there are other changes needed to make it work, but is in progress currently)

Closes [darling#1625](https://github.com/darlinghq/darling/issues/1625)

### CODE REVIEW

File: src/pkg/DistributionXml.cpp [hunk 1]
```diff
@@ -128,9 +128,16 @@ bool DistributionXml::package(const std::string& id, DistributionXml::PkgRef& pk
...
 		if (pkg.path.empty() && node->children && node->children->type == XML_TEXT_NODE && !xmlIsBlankNode(node->children))
 			pkg.path = (char*) node->children->content;
+
+		std::string encodedSpaceTerm = "%20";
+		size_t spacePosition = pkg.path.find(encodedSpaceTerm);
+
+		while (spacePosition != std::string::npos) {
+			pkg.path.replace(spacePosition, 3, " ");
+			spacePosition = pkg.path.find(encodedSpaceTerm);
+		}
```
Comment (CuriousTommy) [inline src/pkg/DistributionXml.cpp]: It would be better if we rely on a method to handle decoding the URL instead. Otherwise, [we would have to manually deal with converting all of the `%` encodings](https://en.wikipedia.org/wiki/Percent-encoding#Reserved_characters)

One idea is to use `NSUrl` (we can convert the file into a objective-C++ file)

**Review by CuriousTommy — CHANGES_REQUESTED** [review]

File: src/pkg/DistributionXml.cpp (hunk 1 above)
Comment (jlucfarias) [reply src/pkg/DistributionXml.cpp]: I found [`-[NSString stringByRemovingPercentEncoding]`](https://developer.apple.com/documentation/foundation/nsstring/removingpercentencoding?language=objc). Will submit the PR with the implementation soon

**Review by CuriousTommy — APPROVED** [review]
LGTM!
